chore: improve error reporting in `main.rs`
Before:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', cmd/src/main.rs:102:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After:
```
Error:
   0: samples/timestamp.log
   1: No such file or directory (os error 2)

Location:
   cmd/src/main.rs:106
```

Don't require `<expr>` argument in `--server` mode.